import {  useFetchMenuItem } from '@/apis/menu-item';
import ProductDetailsContainer from '@/containers/ProductDetails';
import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { ArrowRightIcon } from '@/components/Icons';
import { MenuItem } from '@/types';

const ProductDetails:React.FC<any> = () => {
  const {query, back} = useRouter();
  const {data, isLoading} = useFetchMenuItem(query?.slug)

  const [product, setProduct] = useState<MenuItem>({})
  useEffect(()=>{
    if(data){
      setProduct(data)
    }
  },[data])
  return (
    <>
      <Head>
        <title>Restaurant App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='absolute z-10 flex items-center justify-center ml-4 rounded-full w-14 h-14 bg-full-dark hover:bg-gray-800 top-4' onClick={back} >
          <ArrowRightIcon/>
        </div>
      <main className=' mx-auto max-w-[640pt] bg-full-dark h-max' >
        <ProductDetailsContainer product={product} isLoading={isLoading} />
      </main>
    </>
  );
};



export default ProductDetails;
